# roles/common/main.yml
---
- name: Install common packages
  yum: pkg={{item}} state=installed
  with_items:
    - libselinux-python
    - gedit
    - git
    - tree
    - nano
    
- name: activate selinux enforcing
  selinux: state=enforcing policy=targeted

- name: Enable Firewall
  service: name=firewalld state=running enabled=true
