# roles/web/main.yml
---
- name: Install Apache
  yum: pkg={{item}} state=installed
  with_items:
    - httpd
    - php
    - php-xml
    - php-mysql
- name: Start Apache Service
  service: name=httpd state=running enabled=yes
