# site.yml
---

#Rollen die op de eerste server mogen geinstalleerd worden : Dit is de webserver : WWW
- hosts: spu010
  sudo: true
  roles:
    - common
    - db
    - web

#Rollen die op de tweede server mogen geinstalleerd worden : Dit is de DNS server : NS1
- hosts: spu001
  sudo: true
  roles:
    - common
    - bind
